### ISSUE TITLE
感谢您们非常有趣的工作，想冒昧请教一下关于Restaurant数据集的结果的复现问题。

### ISSUE THREAD

**Issue by LittleSummer114** [leekum2018/CLE4ATE#1]
您好，我们最近也在做aspect term extraction (ATE) 方面的工作，您们的工作非常非常有趣，给了我们很多启发，希望有机会能follow你们的工作继续做好ATE这个任务。
我们最近在re-run您这边提供的代码的时候，在laptop数据集能取得类似的效果，在Restaurant数据集的话，会有些许差距，想请教一下在Laptop数据集和Restaurant数据集用的参数是否会不一样，在Restaurant数据集上，epoch最后设置为多少，以及随机种子需要修改成其他吗？
期待您的回复，

**Comment by chenjx56** [comment]
您好，请问您的问题得到解决了吗

**Comment by LittleSummer114** [comment]
感谢您的来信。
